//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public System.Guid Id { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public System.Guid StudentId { get; set; }
        public string Remarks { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
