//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public System.Guid Id { get; set; }
        public string BookNumber { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> AuthorId { get; set; }
        public string Subject { get; set; }
        public Nullable<System.Guid> PublisherId { get; set; }
        public Nullable<System.Guid> ISBNNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedById { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
