//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMovement
    {
        public System.Guid Id { get; set; }
        public System.Guid BookId { get; set; }
        public System.Guid StudentId { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public long IssueStatus { get; set; }
        public long ReturnStatus { get; set; }
        public string CreatedById { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
