//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public System.Guid Id { get; set; }
        public System.Guid ExpenseTypeId { get; set; }
        public decimal ExpenseAmount { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public string Description { get; set; }
        public string ReceiptAttachment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedById { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ExpenseType ExpenseType { get; set; }
    }
}
