//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradingTechnical
    {
        public System.Guid Id { get; set; }
        public double FromMarks { get; set; }
        public double ToMarks { get; set; }
        public string GradeName { get; set; }
        public double Points { get; set; }
        public string CreatedById { get; set; }
        public string UpdatedById { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
