//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveSheet
    {
        public System.Guid Id { get; set; }
        public System.Guid StudentId { get; set; }
        public string CreatedById { get; set; }
        public System.DateTime DateTimeOut { get; set; }
        public System.DateTime DatetTimeIn { get; set; }
        public string Reasons { get; set; }
        public string AuthorisedById { get; set; }
        public byte RecordStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Student Student { get; set; }
    }
}
