//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Data.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentEntities : DbContext
    {
        public StudentEntities()
            : base("name=StudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AdmissionNumber> AdmissionNumbers { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<BookMovement> BookMovements { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Examination> Examinations { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<ExpenseType> ExpenseTypes { get; set; }
        public virtual DbSet<FeeType> FeeTypes { get; set; }
        public virtual DbSet<fileUpload> fileUploads { get; set; }
        public virtual DbSet<Furniture> Furnitures { get; set; }
        public virtual DbSet<GradingHumanity> GradingHumanities { get; set; }
        public virtual DbSet<GradingLanguage> GradingLanguages { get; set; }
        public virtual DbSet<GradingMathematic> GradingMathematics { get; set; }
        public virtual DbSet<GradingScience> GradingSciences { get; set; }
        public virtual DbSet<GradingTechnical> GradingTechnicals { get; set; }
        public virtual DbSet<Hostel> Hostels { get; set; }
        public virtual DbSet<Instituiton> Instituitons { get; set; }
        public virtual DbSet<InstitutionClass> InstitutionClasses { get; set; }
        public virtual DbSet<IssuedFurniture> IssuedFurnitures { get; set; }
        public virtual DbSet<LeaveSheet> LeaveSheets { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<ResultsAgriculture> ResultsAgricultures { get; set; }
        public virtual DbSet<ResultsArtDesign> ResultsArtDesigns { get; set; }
        public virtual DbSet<ResultsBiology> ResultsBiologies { get; set; }
        public virtual DbSet<ResultsBuildingConstruction> ResultsBuildingConstructions { get; set; }
        public virtual DbSet<ResultsBusiness> ResultsBusinesses { get; set; }
        public virtual DbSet<ResultsChemistry> ResultsChemistries { get; set; }
        public virtual DbSet<ResultsComputerStudy> ResultsComputerStudies { get; set; }
        public virtual DbSet<ResultsCRE> ResultsCREs { get; set; }
        public virtual DbSet<ResultsEnglish> ResultsEnglishes { get; set; }
        public virtual DbSet<ResultsFrench> ResultsFrenches { get; set; }
        public virtual DbSet<ResultsGeography> ResultsGeographies { get; set; }
        public virtual DbSet<ResultsGerman> ResultsGermen { get; set; }
        public virtual DbSet<ResultsHistory> ResultsHistories { get; set; }
        public virtual DbSet<ResultsHomeScience> ResultsHomeSciences { get; set; }
        public virtual DbSet<ResultsKiswahili> ResultsKiswahilis { get; set; }
        public virtual DbSet<ResultsMath> ResultsMaths { get; set; }
        public virtual DbSet<ResultsMusic> ResultsMusics { get; set; }
        public virtual DbSet<ResultsPhysic> ResultsPhysics { get; set; }
        public virtual DbSet<Stream> Streams { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<SubjectCategory> SubjectCategories { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
    }
}
